global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3001']
    metrics_path: /metrics

  - job_name: 'campaign-service'
    static_configs:
      - targets: ['campaign-service:3002']
    metrics_path: /metrics

  - job_name: 'pledge-service'
    static_configs:
      - targets: ['pledge-service:3003']
    metrics_path: /metrics

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:3004']
    metrics_path: /metrics

  - job_name: 'totals-service'
    static_configs:
      - targets: ['totals-service:3005']
    metrics_path: /metrics

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:3006']
    metrics_path: /metrics

  - job_name: 'gateway'
    static_configs:
      - targets: ['nginx-exporter:9113']
    metrics_path: /metrics
